apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
